name: Roll Dice

on: [workflow_dispatch]

jobs:
  roll-dice:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Output Result
        run: echo "Test Output"
