name: Roll Dice

on:
  workflow_dispatch:
    inputs:
      number_of_dice:
        description: 'Number of dice'
        required: true
        default: '1'
      number_of_sides:
        description: 'Number of sides per die'
        required: true
        default: '6'

jobs:
  roll-dice:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Roll Dice
        id: roll
        run: |
          num_dice=${{ github.event.inputs.number_of_dice }}
          num_sides=${{ github.event.inputs.number_of_sides }}

          results=()
          for ((i=1; i<=num_dice; i++))
          do
            roll=$(( (RANDOM % num_sides) + 1 ))
            results+=($roll)
          done
          
          result_str=$(IFS=,; echo "${results[*]}")
          echo "Rolled $num_dice dice with $num_sides sides: $result_str"

          # Set output variable
          echo "results=$result_str" >> $GITHUB_OUTPUT

      - name: Output Result
        run: echo "Dice roll results: ${{ steps.roll.outputs.results }}"
