name: Roll Dice

on: [workflow_dispatch]

jobs:
  roll-dice:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install random
      
      - name: Roll Dice
        id: roll
        run: |
          import random
          import os

          num_dice = int(os.getenv('NUMBER_OF_DICE', '1'))
          num_sides = int(os.getenv('NUMBER_OF_SIDES', '6'))

          results = [random.randint(1, num_sides) for _ in range(num_dice)]
          result_str = ', '.join(map(str, results))

          print(f"Rolled {num_dice} dice with {num_sides} sides: {result_str}")

          # Set output variable
          with open(os.getenv('GITHUB_OUTPUT'), 'a') as fh:
              print(f"results={result_str}", file=fh)
      
      - name: Output Result
        run: echo "Dice roll results: ${{ steps.roll.outputs.results }}"
