name: Roll Dice

on: [workflow_dispatch]

jobs:
  roll-dice:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Roll Dice
        id: roll
        run: |
          num_dice=${{ github.event.inputs.number_of_dice }}
          num_sides=${{ github.event.inputs.number_of_sides }}


      - name: Output Result
        run: echo "Test output"
